# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/artpy',
                'doc_host': 'https://leemengtaiwan.github.io',
                'git_url': 'https://github.com/leemengtaiwan/artpy',
                'lib_path': 'artpy'},
  'syms': {'artpy.core': {'artpy.core.foo': ('core.html#foo', 'artpy/core.py')}}}