# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/archive.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/archive.ipynb 4
# vae = AutoencoderKL.from_pretrained(HF_SD_MODEL, subfolder="vae")
# tokenizer = CLIPTokenizer.from_pretrained(HF_SD_MODEL, subfolder="tokenizer")
# text_encoder = CLIPTextModel.from_pretrained(HF_SD_MODEL, subfolder="text_encoder")
# unet = UNet2DConditionModel.from_pretrained(HF_SD_MODEL, subfolder="unet")

# scheduler = LMSDiscreteScheduler(
#     beta_start=0.00085, beta_end=0.012, beta_schedule="scaled_linear", num_train_timesteps=1000)


# vae = vae.to(device)
# text_encoder = text_encoder.to(device)
# unet = unet.to(device);
