# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/experimental.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/experimental.ipynb 4
from diffusers import StableDiffusionPipeline
import torch
import tempfile
import os
import io
import base64


import pydantic


from datascience_toolkits.fastapi import create_app, serve
