# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/serve.ipynb.

# %% auto 0
__all__ = ['route_info', 'app']

# %% ../nbs/serve.ipynb 3
from datascience_toolkits.fastapi import create_app, serve
from .core import text2image

# %% ../nbs/serve.ipynb 4
route_info = [{
    "path": "/",
    "method": "post",
    "endpoint": text2image
}]

app = create_app(route_info)
serve(app, port=8000)
